# Contains global Spbuilder configuration
global:
  technology:         drupal
  technology_version: 8
  log_dir:     build/logs
  package_dir: build/dist
  clean: true
 
# Quality tools configuration
tools:
  phpcs:
    standard: vendor/smile/php-codesniffer-rules/src/SmileDrupal8
    files:
      - src/modules/custom
    extensions:
      - php
      - module
      - install
      - theme
    ignores:
      - "*src/Tests/*"
      - "*/tests/*"
  phplint:
    files:
      - src/modules/custom
  phpmd:
    files:
      - src/modules/custom
    rulesets:
      - vendor/smile/php-md-rules/resources/rulesets/Drupal/cleancode.xml
      - codesize
      - design
      - vendor/smile/php-md-rules/resources/rulesets/Drupal/naming.xml
      - vendor/smile/php-md-rules/resources/rulesets/Drupal/unusedcode.xml
  phpcpd:
    files:
      - src/modules/custom
  visualization:
    files: src/
    hostname: localhost
    port: 8080

# Package creation
package:
  format: tar.gz                  # Package format (availables : tar, tar,gz, tar.bz2, zip, phar, none)
  artefact: package-name          # (Optional) Package name (default is composer's <vendorName>-<projectName>
  commands:                       # Commands to run during packaging
    - composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction --ignore-platform-reqs
    - composer run-script drupal-scaffold # for scaffolding (index.php, etc) not included when already composer.lock
  excludes:                       # Path to exclude from package
    - ./architecture
    - ./build
    - ./docs
    - ./scripts
    - ./lxcfile
    - ./CONTRIBUTING.md
    - ./COPYING.txt
    - ./ISSUE_TEMPLATE.md
    - ./README.md
    - ./.gitignore
    - ./.php_cs
    - ./.spbuilder.yml
    - ./.travis.yml
    - ./package.json
    - ./Gruntfile.js
    - .htaccess
  skipRoot: true
  vcs:
    type: git                     # VCS Type (availables : git, svn)
    url: ~                        # Repository URL (default to local git repo, with .git extension, not the https one)
