---
- hosts: webservers

  vars:
    ansible_user: "{{ drupal_project_user }}"

  tasks:
  - fail:
      msg: "You must provide a 'status' variable in --extra-vars"
    when: status is not defined or status == ""

  - fail:
      msg: "'status' must equals to 'enable' or 'disable'."
    when: status != "enable" and status != "disable"

  - include: includes/set-maintenance-tasks.yml
    vars:
      maintenance_mode: "{{ status }}"
      delivery_mode: false